repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest unit
        entry: pytest tests/unit -v --tb=short -x -n auto
        language: system
        pass_filenames: false
        stages: [pre-push]
