global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "ragin-gateway"
    static_configs:
      - targets: ["gateway:9090"]
    metrics_path: "/metrics"

  - job_name: "ragin-chrollo"
    static_configs:
      - targets: ["chrollo:8081"]
    metrics_path: "/metrics"

  - job_name: "ragin-don"
    static_configs:
      - targets: ["don:8082"]
    metrics_path: "/metrics"

  - job_name: "ragin-hisoka"
    static_configs:
      - targets: ["hisoka:8083"]
    metrics_path: "/metrics"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"
